server {
	set $template_root /var/ipax/templates;

	include /var/ipax/conf/location_norobots.conf;
	include /var/ipax/conf/location_health.conf;

	location / {
		add_header Cache-Control no-store;
		add_header Pragma no-cache;
		default_type text/html;
		content_by_lua_block {
			require("resty.template").render_file("proxy.html")
		}
	}
}
include /var/ipax/conf/filter_cookie.conf;
include /var/ipax/proxy_conf.d/*.conf;
