services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:25.0
    restart: always
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: update-email
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    command: "start-dev --import-realm"
  demoapps:
    container_name: demoapps
    image: ghcr.io/identicum/ipax:latest
    pull_policy: always
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
    volumes:
      - ../lua/:/etc/ipax/lua/
      - ../conf/nginx.conf.template:/usr/local/openresty/nginx/conf/nginx.conf.template
      - ../conf/demoapp.conf:/usr/local/openresty/nginx/conf/demoapp.conf
      - ../conf/demoapp_default_variables.conf:/usr/local/openresty/nginx/conf/demoapp_default_variables.conf
      - ../templates:/var/ipax/templates/
      - ./server.conf:/usr/local/openresty/nginx/conf/server.conf
      - ./conf.d/:/etc/ipax/conf.d/
    depends_on:
      idp:
        condition: service_healthy
  mailcatcher:
    container_name: mailcatcher
    image: ghcr.io/identicum/mailcatcher:latest
    restart: always
    ports:
      - 1080:1080