version: '3'

services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:22.0
    restart: always
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: update-email
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    command: "start-dev --import-realm"
  ipax:
    container_name: ipax
    image: ghcr.io/identicum/ipax:latest
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
      OIDC_DISCOVERY: http://idp:8080/realms/demorealm/.well-known/openid-configuration
      OIDC_CLIENT_ID: ipax_client_id
      OIDC_USE_PKCE: "false"
      OIDC_CLIENT_SECRET: ipax_client_secret
      OIDC_SCOPE: openid profile email roles phone
      OIDC_POST_LOGOUT_REDIRECT_URI: http://localhost/logoutSuccess.html
      KC_DELETE_ACCOUNT_ACTION: delete_account
      KC_DELETE_ACCOUNT_LABEL: Delete user
      KC_UPDATE_EMAIL_ACTION: UPDATE_EMAIL
      KC_UPDATE_PASSWORD_ACTION: UPDATE_PASSWORD
    volumes:
      - ./conf/info.conf:/usr/local/openresty/nginx/conf/info.conf
      - ./conf/lua.conf:/usr/local/openresty/nginx/conf/lua.conf
      - ./conf/nginx.conf.template:/usr/local/openresty/nginx/conf/nginx.conf.template
      - ./conf/norobots.conf:/usr/local/openresty/nginx/conf/norobots.conf
      - ./conf/server.conf:/usr/local/openresty/nginx/conf/server.conf
      - ./html/:/var/ipax/html/
      - ./lua/:/etc/ipax/lua/
      - ./templates:/var/ipax/templates/
    depends_on:
      idp:
        condition: service_healthy
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher:latest
    restart: always
    ports:
      - 1080:1080