version: '3'

services:
  idp:
    container_name: idp
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
    volumes:
      - ./keycloak/startup-scripts/:/opt/jboss/startup-scripts/
      - ./keycloak/custom-scripts/:/opt/jboss/custom-scripts/
      - ./keycloak/objects/:/opt/jboss/keycloak/objects/
    ports:
      - 8080:8080
  ipax:
    container_name: ipax
    image: identicum/ipax:latest
    restart: always
    volumes:
      - ./conf/info.conf:/usr/local/openresty/nginx/conf/info.conf
      - ./conf/lua.conf:/usr/local/openresty/nginx/conf/lua.conf
      - ./conf/nginx.conf.template:/usr/local/openresty/nginx/conf/nginx.conf.template
      - ./conf/server.conf:/usr/local/openresty/nginx/conf/server.conf
      - ./html/:/var/ipax/html/
      - ./lua/:/etc/ipax/lua/
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
      OIDC_DISCOVERY: http://idp:8080/auth/realms/demorealm/.well-known/openid-configuration
      OIDC_CLIENT_ID: ipax_client_id
      OIDC_USE_PKCE: "false"
      OIDC_CLIENT_SECRET: ipax_client_secret
      OIDC_SCOPE: openid profile email roles phone
      OIDC_POST_LOGOUT_REDIRECT_URI: http://localhost/logoutSuccess.html
      OIDC_ACR_VALUES: "loa-2"
    ports:
      - 80:80
