services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:26.2
    restart: always
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_FEATURES: update-email
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    command: "start-dev --import-realm"
  demoapps:
    container_name: demoapps
    image: ghcr.io/identicum/ipax:latest
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
    volumes:
      - ../../conf/:/etc/ipax/conf/
      - ./conf.d/:/etc/ipax/conf/multi/host/conf.d/
      - ../../html/:/var/ipax/html/
      - ../../lua/:/etc/ipax/lua/
      - ../../templates:/var/ipax/templates/
    depends_on:
      idp:
        condition: service_healthy
  mailcatcher:
    container_name: mailcatcher
    image: ghcr.io/identicum/mailcatcher:latest
    restart: always
    ports:
      - 1080:1080