server {
	include /var/ipax/conf/location_norobots.conf;
	server_name demoapp1;
	set $oidc_redirect_uri 'http://demoapp1/private/redirect_uri';

	location / {
		access_by_lua_block {
			local ipax = require "ipax"
			local oidc_opts = ipax.get_oidc_opts()
			local session_opts = ipax.get_session_opts()
			ngx.ctx.res = ipax.get_res(oidc_opts, session_opts);
			local user = ipax.get_user(ngx.ctx.res)
		}
		proxy_pass http://app1:80/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
