name: ipax-single

services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:26.2
    restart: always
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_FEATURES: update-email
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    command: "start-dev --import-realm"

  ipax:
    container_name: ipax
    image: ghcr.io/identicum/ipax:refactor
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
      OIDC_DISCOVERY: http://idp:8080/realms/demorealm/.well-known/openid-configuration
      OIDC_CLIENT_ID: ipax_client_id
      OIDC_CLIENT_SECRET: ipax_client_secret
      OIDC_SCOPE: openid profile email roles phone
      IPAX_DEMOAPP_NAME: demoapp1
      IPAX_DISPLAY_NAME: IPAx single demoapp
      IPAX_BASE_URL: http://demoapp1
      IPAX_MODE: single
      KC_DELETE_ACCOUNT_ACTION: delete_account
      KC_DELETE_ACCOUNT_LABEL: Delete user
      KC_UPDATE_EMAIL_ACTION: UPDATE_EMAIL
      KC_UPDATE_PASSWORD_ACTION: UPDATE_PASSWORD
    volumes:
      - ../../entrypoint.sh:/entrypoint.sh
      - ../../conf/:/var/ipax/conf/
      - ../../html/:/var/ipax/html/
      - ../../lua/:/var/ipax/lua/
      - ../../templates:/var/ipax/templates/
    depends_on:
      idp:
        condition: service_healthy
  
  mailcatcher:
    container_name: mailcatcher
    image: ghcr.io/identicum/mailcatcher:latest
    restart: always
    ports:
      - 1080:1080
