on:
  push:
    branches:
    - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build image 
      run: docker build -t identicum/${{ github.repository.name }}:latest .
      working-directory: .
    - name: Push to Docker Hub
      run: docker push identicum/${{ github.repository.name }}:latest
