name: GHCR

on:
  push:
    branches:
    - main
    paths:
    - 'conf/**'
    - 'html/**'
    - 'lua/**'
    - 'templates/**'
    - Dockerfile
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/identicum/${{github.event.repository.name}}:latest
        platforms: linux/amd64,linux/arm64