on:
  push:
    branches:
      - main
env:
  CONTAINER_IMAGE: ghcr.io/identicum/${{github.event.repository.name}}:latest
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and Push
      run: docker buildx build -t ${{env.CONTAINER_IMAGE}} --push --platform=linux/arm64,linux/amd64 .
